<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [JDEV] Delivery error when setting up for new transport
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:jdev%40jabber.org?Subject=Re%3A%20%5BJDEV%5D%20Delivery%20error%20when%20setting%20up%20for%20new%20transport&In-Reply-To=%3C20011212150611.Q10457%40cobalt.ph.inter.net%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="039682.html">
   <LINK REL="Next"  HREF="039672.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[JDEV] Delivery error when setting up for new transport</H1>
    <B>Migs Paraz</B> 
    <A HREF="mailto:jdev%40jabber.org?Subject=Re%3A%20%5BJDEV%5D%20Delivery%20error%20when%20setting%20up%20for%20new%20transport&In-Reply-To=%3C20011212150611.Q10457%40cobalt.ph.inter.net%3E"
       TITLE="[JDEV] Delivery error when setting up for new transport">map at internet.org.ph
       </A><BR>
    <I>Wed Dec 12 01:06:11 CST 2001</I>
    <P><UL>
        <LI>Previous message: <A HREF="039682.html">[JDEV] BUG REPORT: pthsock/makefile
</A></li>
        <LI>Next message: <A HREF="039672.html">[JDEV] Delivery error when setting up for new transport
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#39671">[ date ]</a>
              <a href="thread.html#39671">[ thread ]</a>
              <a href="subject.html#39671">[ subject ]</a>
              <a href="author.html#39671">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,
I'm writing a Python SMS component based on the sample code.
But, the server rejects the client when logging in.  

I've only added:

      &lt;browse&gt;

        &lt;service type=&quot;sms&quot; jid=&quot;sms.localhost&quot; name=&quot;SMS Gateway&quot;&gt;
          &lt;ns&gt;jabber:iq:gateway&lt;/ns&gt;
        &lt;/service&gt;

and:

  &lt;service id=&quot;sms&quot;&gt;
    &lt;host&gt;localhost&lt;/host&gt;
    &lt;accept&gt;
      &lt;ip&gt;127.0.0.1&lt;/ip&gt;
      &lt;port&gt;1234&lt;/port&gt;
      &lt;secret&gt;test&lt;/secret&gt;
    &lt;/accept&gt;
  &lt;/service&gt;


The errors:

Wed Dec 12 15:00:26 2001  mio.c:750 MIO read from socket 11: &lt;iq id='A0' type='get'&gt;&lt;query xmlns='jabber:iq:auth'&gt;&lt;username&gt;baloney&lt;/username&gt;&lt;/query&gt;&lt;/iq&gt;
Wed Dec 12 15:00:26 2001  client.c:243 pthsock_client_read called with: m:8109A68 flag:3 arg:8109B58
Wed Dec 12 15:00:26 2001  deliver.c:460 DELIVER 4:localhost &lt;route type='auth' to='<A HREF="http://mail.jabber.org/mailman/listinfo/jdev">baloney at localhost</A>' from='<A HREF="http://mail.jabber.org/mailman/listinfo/jdev">11 at c2s</A>/8109A68'&gt;&lt;iq id='A0' type='get'&gt;&lt;query xmlns='jabber:iq:auth'&gt;&lt;username&gt;baloney&lt;/username&gt;&lt;/query&gt;&lt;/iq&gt;&lt;/route&gt;
Wed Dec 12 15:00:26 2001  deliver.c:579 delivery failed (Unable to deliver, destination unknown)
Wed Dec 12 15:00:26 2001  log.c:105 &lt;log type='notice' from='localhost'&gt;bouncing a routed packet to <A HREF="http://mail.jabber.org/mailman/listinfo/jdev">baloney at localhost</A> from <A HREF="http://mail.jabber.org/mailman/listinfo/jdev">11 at c2s</A>/8109A68: Unable to deliver, destination unknown&lt;/log&gt;
Wed Dec 12 15:00:26 2001  deliver.c:460 DELIVER 3:localhost &lt;log type='notice' from='localhost'&gt;bouncing a routed packet to <A HREF="http://mail.jabber.org/mailman/listinfo/jdev">baloney at localhost</A> from <A HREF="http://mail.jabber.org/mailman/listinfo/jdev">11 at c2s</A>/8109A68: Unable to deliver, destination unknown&lt;/log&gt;
Wed Dec 12 15:00:26 2001  deliver.c:651 delivering to instance 'elogger'
20011212T07:00:26: [notice] (localhost): bouncing a routed packet to <A HREF="http://mail.jabber.org/mailman/listinfo/jdev">baloney at localhost</A> from <A HREF="http://mail.jabber.org/mailman/listinfo/jdev">11 at c2s</A>/8109A68: Unable to deliver, destination unknown
Wed Dec 12 15:00:26 2001  deliver.c:460 DELIVER 4:c2s &lt;route type='error' to='<A HREF="http://mail.jabber.org/mailman/listinfo/jdev">11 at c2s</A>/8109A68' from='<A HREF="http://mail.jabber.org/mailman/listinfo/jdev">baloney at localhost</A>' error='Unable to deliver, destination unknown'&gt;&lt;iq id='A0' type='get'&gt;&lt;query xmlns='jabber:iq:auth'&gt;&lt;username&gt;baloney&lt;/username&gt;&lt;/query&gt;&lt;/iq&gt;&lt;/route&gt;


When I remove my additions to the config file, these errors go away.
What causes these?
I don't have this problem with the JUD transport I wrote earlier.

I'd appreciate help here so I can go on with writing my transport...


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="039682.html">[JDEV] BUG REPORT: pthsock/makefile
</A></li>
	<LI>Next message: <A HREF="039672.html">[JDEV] Delivery error when setting up for new transport
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#39671">[ date ]</a>
              <a href="thread.html#39671">[ thread ]</a>
              <a href="subject.html#39671">[ subject ]</a>
              <a href="author.html#39671">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://mail.jabber.org/mailman/listinfo/jdev">More information about the JDev
mailing list</a><br>
</body></html>
